                    **𝐍𝐮𝐦𝐩𝐲 𝐑𝐚𝐧𝐝𝐨𝐦**             -- 𝐊𝐮𝐧𝐚𝐥 𝐊𝐚𝐩𝐚𝐝𝐞

In [2]:
from numpy import random
x1 = random.rand()
x2 = random.rand(5)
x3 = random.choice([30, 50, 70, 90])
x4 = random.choice([3, 5, 7, 9], size=(3, 3))
x5 = random.randint(100)

print(x1)
print("--------")
print(x2)
print("---------")
print(x3)
print("---------")
print(x4)
print("-----------")
print(x5)

0.24902625905927644
--------
[0.75447644 0.12188665 0.31618359 0.85766834 0.70982355]
---------
50
---------
[[7 3 5]
 [7 9 7]
 [9 3 9]]
-----------
99


- Normal (Gaussian) Distribution:

In [3]:
y1 = random.normal(loc=1, scale=2, size=(3, 2))
y2 = random.binomial(n=10, p=0.5, size=10)
y3 = random.poisson(lam=2, size=10)
y4 = random.uniform(size=(3, 2))
y5 = random.logistic(loc=1, scale=2, size=(3, 2))

print(y1)
print("--------")
print(y2)
print("--------")
print(y3)
print("--------")
print(y4)
print("--------")
print(y5)

[[-0.21459552  2.74530352]
 [ 2.42896617  0.57899434]
 [ 2.8118457  -0.59744633]]
--------
[4 6 5 7 5 2 2 5 5 5]
--------
[3 0 2 1 1 1 2 2 1 2]
--------
[[0.10291113 0.64151115]
 [0.38813246 0.50692994]
 [0.09061382 0.16890667]]
--------
[[-2.25057437 -2.41980695]
 [ 5.9295599  -0.68689022]
 [-1.97812384  3.74278595]]
